# Generated by Django 5.1 on 2024-09-02 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.cidade')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matricula.curso')),
            ],
        ),
    ]
